name: Deploy P4C Static Site

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate Files
      run: |
        echo "📋 Static files found:"
        ls -la *.html 2>/dev/null || echo "No HTML files found"
        ls -la *.js 2>/dev/null || echo "No JS files found"
        ls -la *.css 2>/dev/null || echo "No CSS files found"
        if [ -f "CNAME" ]; then echo "✅ CNAME file found"; fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
